# Generated by Django 5.1.4 on 2024-12-28 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Disease Name')),
                ('description', models.TextField(verbose_name='Disease Description')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Uploaded Image')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Upload Time')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Symptom Name')),
                ('description', models.TextField(verbose_name='Symptom Description')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Confidence Level')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Diagnosis Time')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.disease', verbose_name='Diagnosed Disease')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.image', verbose_name='Related Image')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(to='classifier.symptom', verbose_name='Symptoms'),
        ),
    ]
