# Generated by Django 5.1.4 on 2025-01-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='dn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
