# Generated by Django 5.1.4 on 2025-01-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_alter_diagnosis_image_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(blank=True, null=True, to='classifier.symptom', verbose_name='Symptoms'),
        ),
    ]
