# Generated by Django 5.1.4 on 2025-01-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_alter_disease_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(default='martiin'),
            preserve_default=False,
        ),
    ]
