# Generated by Django 5.1.4 on 2025-02-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_remove_disease_symptoms_delete_symptom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='notes',
            field=models.TextField(default='ote'),
            preserve_default=False,
        ),
    ]
